spring:
  application:
    name: tracekit-demo-app

server:
  port: 8080

tracekit:
  enabled: true
  api-key: ctxio_c16d0728ea99bbd5b849c6341e49dff99263018a19992faafe815e76b01dee97
  service-name: javasdk
  environment: development
  endpoint: https://app.tracekit.dev
  enable-code-monitoring: true
  local-ui-port: 9999

logging:
  level:
    root: INFO
    dev.tracekit: DEBUG
    org.springframework.web: INFO
    io.opentelemetry: DEBUG
    io.opentelemetry.exporter: TRACE
