spring:
  application:
    name: tracekit-kotlin-demo

server:
  port: 8082

tracekit:
  enabled: true
  api-key: ctxio_0fe8fb7749f225cf8a88a8ba7d36881a015734e0fd12e350f77b131e0c4da794
  service-name: kotlin-sdk
  environment: development
  endpoint: http://localhost:8081
  enable-code-monitoring: true
  local-ui-port: 9999

logging:
  level:
    root: INFO
    dev.tracekit: DEBUG
    org.springframework.web: INFO
